# Generated by Django 2.1.7 on 2019-03-05 05:18

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name or title')),
                ('description', models.TextField(verbose_name='Description')),
                ('code', models.CharField(max_length=15, verbose_name='Product code')),
                ('available_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Available price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Old price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=main.models.upload_to_code_product)),
                ('hash', models.CharField(max_length=30, verbose_name='Image hash')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is main?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=True, related_name='images', to='main.Product')),
            ],
        ),
    ]
